- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.shell: shell
    ~/.zshrc: zshrc

- create: []

- shell:
  - git submodule sync --recursive
  - git update-submodules --recursive