- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.shell: shell
    ~/.zshrc: zshrc
    ~/.expedia: expedia/dotfiles
    ~/.ssh/config: expedia/dotfiles/ssh/config

- create: []

- shell:
  - cp -Rv expedia/dotfiles/bin/ /usr/local/bin
  - git submodule sync --recursive
  - git update-submodules --recursive